export const SET_CURRENT_MAP_CENTER = 'SET_CURRENT_MAP_CENTER';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SUBMIT_EVENT = 'SUBMIT_EVENT';
